
package gui;

import java.awt.*;
import javax.swing.*;

public class LabelTest extends javax.swing.JFrame {

    private JLabel label1;
    private JLabel label2;
    private JTextField textField1;
    private JButton plainButton;
    private JButton fancyButton;
    private JTextArea Textbox1;
    private JRadioButton b1, b2, b3;
    private JComboBox ComboBox;
    private JCheckBox cb1, cb2;
    
    public LabelTest() {
        
        //Label with text
        Container container = getContentPane();
        container.setLayout(new FlowLayout());
        label1 = new JLabel("Label with text");
        container.add(label1);
        setSize(275, 200);
        setVisible(true);
        
        //Label icon
        Icon rabbit = new ImageIcon("C:\\Users\\ainnuraida\\Downloads\\rabbit.gif");
        
        label2 = new JLabel("Label with text and icon", rabbit,SwingConstants.CENTER);

        container.add(label2);
        
        //text field
        textField1 = new JTextField(10);
        container.add(textField1);
        
        //plain button
        //plainButton = new JButton("Plain Button");
        //container.add(plainButton);
        
        //fancy button
        ImageIcon tele = new ImageIcon("C:\\Users\\ainnuraida\\Downloads\\SEMESTER 3\\SPG 0453\\coding\\GUI\\src\\gui\\tele.png");
        
        Image teleImage = tele.getImage();
        Image resizedImage = teleImage.getScaledInstance(50, 40, java.awt.Image.SCALE_SMOOTH);
        
        ImageIcon resizedIcon = new ImageIcon(resizedImage);
        
        fancyButton = new JButton ("Teletubbies button", resizedIcon);
        container.add(fancyButton);
        
        //text box (text area)
        
        Textbox1 = new JTextArea ("Multiple line");
        Textbox1.setSize(100,200);
        Textbox1.setLocation(20,20);
        Textbox1.setBackground(Color.BLACK);
        Textbox1.setForeground(Color.PINK);
        Textbox1.setFont(new Font("Bookman", Font.TRUETYPE_FONT,12));
        add(Textbox1);
        
        //radio button
        ButtonGroup group1 = new ButtonGroup();
        
        b1 = new JRadioButton("Haagen Dazz");
        b2 = new JRadioButton("Baskin Robin");
        b3 = new JRadioButton("Mixue");
        
        b1.setBounds(20, 20, 200, 50);
        b2.setBounds(20, 70, 200, 50);
        b3.setBounds(20, 110, 200, 50);
        
        container.add(b1);
        container.add(b2);
        container.add(b3);
        
        //combo box
        String name[]= {"kuih.gif", "kuih1.gif", "kuih3.gif"};
        ComboBox = new JComboBox(name);
        ComboBox.setMaximumRowCount(3);
        ComboBox.setBounds (50, 50, 100, 20);
        add(ComboBox);
        
        cb1 = new JCheckBox("C");
        cb2 = new JCheckBox("JAVA");
        
        cb1.setBounds(20, 20, 200, 50);
        cb2.setBounds(20, 70, 200, 50);
        
        add(cb1);
        add(cb2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LabelTest application = new LabelTest();
        application.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabelTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
